# Generated by Django 2.1.7 on 2019-04-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20190316_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='act_user',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
