# Generated by Django 2.1.7 on 2019-06-17 10:10

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_classes_act_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=50, verbose_name='概要')),
                ('description', models.TextField(blank=True, verbose_name='詳細な説明')),
                ('start_time', models.TimeField(default=datetime.time(7, 0), verbose_name='開始時間')),
                ('end_time', models.TimeField(default=datetime.time(7, 0), verbose_name='終了時間')),
                ('date', models.DateField(verbose_name='日付')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
        migrations.AlterField(
            model_name='classes',
            name='grade',
            field=models.CharField(choices=[('小1', '小1'), ('小2', '小2'), ('小3', '小3'), ('小4', '小4'), ('小5', '小5'), ('小6', '小6'), ('中1', '中1'), ('中2', '中2'), ('中3', '中3'), ('高１', '高１'), ('高2', '高2'), ('高3', '高3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='classes',
            name='subject',
            field=models.CharField(choices=[('国語', '国語'), ('数学', '数学'), ('英語', '英語'), ('理科', '理科'), ('社会', '社会')], max_length=100),
        ),
        migrations.AlterField(
            model_name='classes',
            name='time',
            field=models.TimeField(choices=[('10:50', '10:50'), ('12:50', '12:50'), ('14:20', '14:20'), ('15:50', '15:50'), ('17:20', '17:20'), ('18:50', '18:50'), ('20:20', '20:20')]),
        ),
    ]
